-- MySQL Script generated by MySQL Workbench
-- Sun Aug  6 00:23:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fiscalize
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fiscalize
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fiscalize` DEFAULT CHARACTER SET utf8 ;
USE `fiscalize` ;

-- -----------------------------------------------------
-- Table `fiscalize`.`cota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`cota` (
  `cotaId` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cotaId`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fiscalize`.`partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`partido` (
  `partidoId` INT(11) NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`partidoId`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fiscalize`.`parlamentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`parlamentar` (
  `parlamentarId` INT(11) NOT NULL AUTO_INCREMENT,
  `partidoId` INT(11) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `nomeCivil` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(500) NULL DEFAULT NULL,
  `profissao` VARCHAR(200) NULL DEFAULT NULL,
  `ideCadastro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`parlamentarId`),
  CONSTRAINT `fk_Parlamentar_Partido1`
    FOREIGN KEY (`partidoId`)
    REFERENCES `fiscalize`.`partido` (`partidoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 786
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Parlamentar_Partido1_idx` ON `fiscalize`.`parlamentar` (`partidoId` ASC);


-- -----------------------------------------------------
-- Table `fiscalize`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`uf` (
  `ufId` INT(11) NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(2) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ufId`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `sigla_UNIQUE` ON `fiscalize`.`uf` (`sigla` ASC);


-- -----------------------------------------------------
-- Table `fiscalize`.`notafiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`notafiscal` (
  `notaFiscalId` INT(11) NOT NULL AUTO_INCREMENT,
  `parlamentarId` INT(11) NOT NULL,
  `cotaId` INT(11) NOT NULL,
  `ufId` INT(11) NOT NULL,
  `dataEmissao` DATETIME NULL DEFAULT NULL,
  `descricao` VARCHAR(500) NULL DEFAULT NULL,
  `descricaoSubCota` VARCHAR(500) NULL DEFAULT NULL,
  `beneficiario` VARCHAR(500) NULL DEFAULT NULL,
  `cpfCnpj` VARCHAR(45) NULL DEFAULT NULL,
  `ano` INT(11) NOT NULL,
  `mes` INT(11) NOT NULL,
  `numeroDocumento` VARCHAR(45) NULL DEFAULT NULL,
  `parcela` INT(11) NULL DEFAULT NULL,
  `tipoDocumentoFiscal` INT(11) NOT NULL COMMENT 'Nota Fiscal - 0\nRecibo - 1\nDespesa Exterior - 2\n',
  `nomePassageiro` VARCHAR(500) NULL DEFAULT NULL,
  `trechoViagem` VARCHAR(500) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `valorGlosa` DECIMAL(10,2) NULL DEFAULT NULL,
  `valorLiquido` DECIMAL(10,2) NULL DEFAULT NULL,
  `dataInclusao` DATETIME NOT NULL,
  PRIMARY KEY (`notaFiscalId`),
  CONSTRAINT `fk_NotaFiscal_Cota1`
    FOREIGN KEY (`cotaId`)
    REFERENCES `fiscalize`.`cota` (`cotaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotaFiscal_Parlamentar1`
    FOREIGN KEY (`parlamentarId`)
    REFERENCES `fiscalize`.`parlamentar` (`parlamentarId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notafiscal_Uf1`
    FOREIGN KEY (`ufId`)
    REFERENCES `fiscalize`.`uf` (`ufId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 79368
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_NotaFiscal_Parlamentar1_idx` ON `fiscalize`.`notafiscal` (`parlamentarId` ASC);

CREATE INDEX `fk_NotaFiscal_Cota1_idx` ON `fiscalize`.`notafiscal` (`cotaId` ASC);

CREATE INDEX `fk_notafiscal_Uf1_idx` ON `fiscalize`.`notafiscal` (`ufId` ASC);


-- -----------------------------------------------------
-- Table `fiscalize`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`usuario` (
  `usuarioId` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `facebookId` VARCHAR(45) NULL DEFAULT NULL,
  `tokenId` VARCHAR(100) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `experiente` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`usuarioId`))
ENGINE = InnoDB
AUTO_INCREMENT = 17932
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fiscalize`.`analise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`analise` (
  `analiseId` INT(11) NOT NULL AUTO_INCREMENT,
  `notaFiscalId` INT(11) NOT NULL,
  `responsavelUsuarioId` INT(11) NOT NULL,
  `concluida` TINYINT(1) NOT NULL DEFAULT '0',
  `comentarios` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`analiseId`),
  CONSTRAINT `fk_analise_notafiscal1`
    FOREIGN KEY (`notaFiscalId`)
    REFERENCES `fiscalize`.`notafiscal` (`notaFiscalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analise_usuario1`
    FOREIGN KEY (`responsavelUsuarioId`)
    REFERENCES `fiscalize`.`usuario` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_analise_notafiscal1_idx` ON `fiscalize`.`analise` (`notaFiscalId` ASC);

CREATE INDEX `fk_analise_usuario1_idx` ON `fiscalize`.`analise` (`responsavelUsuarioId` ASC);


-- -----------------------------------------------------
-- Table `fiscalize`.`despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`despesa` (
  `despesaId` INT(11) NOT NULL AUTO_INCREMENT,
  `codLegislatura` VARCHAR(10) NULL DEFAULT NULL,
  `datEmissao` VARCHAR(30) NULL DEFAULT NULL,
  `ideCadastro` VARCHAR(10) NULL DEFAULT NULL,
  `indTipoDocumento` VARCHAR(10) NULL DEFAULT NULL,
  `nuCarteiraParlamentar` VARCHAR(10) NULL DEFAULT NULL,
  `nuLegislatura` VARCHAR(10) NULL DEFAULT NULL,
  `numAno` VARCHAR(10) NULL DEFAULT NULL,
  `numEspecificacaoSubCota` VARCHAR(500) NULL DEFAULT NULL,
  `numLote` VARCHAR(20) NULL DEFAULT NULL,
  `numMes` VARCHAR(10) NULL DEFAULT NULL,
  `numParcela` VARCHAR(10) NULL DEFAULT NULL,
  `numRessarcimento` VARCHAR(10) NULL DEFAULT NULL,
  `numSubCota` VARCHAR(500) NULL DEFAULT NULL,
  `sgPartido` VARCHAR(10) NULL DEFAULT NULL,
  `sgUF` VARCHAR(10) NULL DEFAULT NULL,
  `txNomeParlamentar` VARCHAR(500) NULL DEFAULT NULL,
  `txtCNPJCPF` VARCHAR(20) NULL DEFAULT NULL,
  `txtDescricao` VARCHAR(500) NULL DEFAULT NULL,
  `txtDescricaoEspecificacao` VARCHAR(500) NULL DEFAULT NULL,
  `txtBeneficiario` VARCHAR(500) NULL DEFAULT NULL,
  `txtNumero` VARCHAR(50) NULL DEFAULT NULL,
  `txtPassageiro` VARCHAR(200) NULL DEFAULT NULL,
  `txtTrecho` VARCHAR(500) NULL DEFAULT NULL,
  `vlrDocumento` VARCHAR(20) NULL DEFAULT NULL,
  `vlrGlosa` VARCHAR(20) NULL DEFAULT NULL,
  `vlrLiquido` VARCHAR(20) NULL DEFAULT NULL,
  `dataInclusao` DATETIME NOT NULL,
  PRIMARY KEY (`despesaId`))
ENGINE = InnoDB
AUTO_INCREMENT = 90766
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fiscalize`.`suspeita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalize`.`suspeita` (
  `suspeitaId` INT(11) NOT NULL AUTO_INCREMENT,
  `notaFiscalId` INT(11) NOT NULL,
  `usuarioId` INT(11) NOT NULL,
  `suspeita` TINYINT(1) NOT NULL DEFAULT '0',
  `suspeitaValor` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Valor sob suspeita?',
  `suspeitaObjeto` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Objeto da compra/contratação sob suspeita?',
  `suspeitaBeneficiario` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Fornecedor sob suspeita?',
  `comentarios` VARCHAR(2000) NULL DEFAULT NULL,
  `dataInclusao` DATETIME NOT NULL,
  PRIMARY KEY (`suspeitaId`),
  CONSTRAINT `fk_Suspeita_Usuario1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `fiscalize`.`usuario` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suspeita_notafiscal1`
    FOREIGN KEY (`notaFiscalId`)
    REFERENCES `fiscalize`.`notafiscal` (`notaFiscalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1371766
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Suspeita_notafiscal1_idx` ON `fiscalize`.`suspeita` (`notaFiscalId` ASC);

CREATE INDEX `fk_Suspeita_Usuario1_idx` ON `fiscalize`.`suspeita` (`usuarioId` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
